version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test-service
    overwrite: true
permissions:
  - object: /home/ec2-user/test-service
    mode: 755
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  # ApplicationStop:
  #   - location: scripts/application_stop.sh
  #     timeout: 300
  #     runas: ec2-user
