version: 0.2
phases:
  install:
   commands:
      - echo "install > commands"
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build:prod
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - package.json
    - node_modules/**/*
    # - appspec.yml
    # - scripts/**/*
