name: CI/CD Sopherre-API

on:
  push:
    branches: [main, dev, alpha]
  pull_request:
    branches: [main, dev, alpha]

jobs:
  SetUp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install packages
        run: yarn install

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint